spring:
  application:
    name: vital-view
  datasource:
    url: jdbc:mariadb://vital-view-db:3306/vital_view
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080
  servlet:
    context-path: /main